### PR TITLE
Update of Json schema

### LINKED ISSUE #59: Correct minimum element restrictions in schema
The current schema allows for empty arrays (e.g. `observations`).

### PR DESCRIPTION
**Pull request by rfrsilva**
Closes #59 

Update of Json schema to avoid `observations` and `data` arrays to be empty.
Update of name of a Json file created for testing purposes.
Update of documentation.

### CODE REVIEW

**Comment by nmsa** [comment]
@rfrsilva Does minItems have the correct behaviour?

why is data allowed to have 0?

 ```json
 "data": {
            "$id": "/properties/data",
            "type": "array",
            "minItems": 0,
```

**Comment by nmsa** [comment]
@rfrsilva

**Comment by rfrsilva** [comment]
"minItems" specifies minimum size of the array. To be valid, the array size must greater than, or equal to the value of this keyword.

About data array, i updated the "minItems" keywork to have the value 1.

**Comment by rfrsilva** [comment]
I made some tests and no files are affected by the schema version.
I think that we can merge this branch.

**Pull request merged**
